from kivy.graphics import Color

COLOR_DEFAULD = [1,1,1]
COLOR_SELECTED = [1,1,0]
COLOR_TEXT_CONDITION = [0,0,0]
COLOR_CONNECTOR = [1,0,0]


WIDTH_LIGHTER = 3
FONT_SIZE_LABEL_CONDITION = 60



RADIUS_CONDITION = 50
RADIUS_CONNECTOR = 5